# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TimeBus
email: robsonalves.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Todos os horários de onibus de sua cidade ao seu alcance.
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site
github_username:  timebus

# Build settings
markdown: kramdown
